title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:  unix_commands   # the name of the repository when it is created for the learner
  repo:  unix_commands_template   # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: Listing files - *ls* command
- title: List files with `ls` command
  description: Basic UNIC command for lisitng files, folders
  event: pull_request.synchronize
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: Options for listing files
# - title: Do more with `ls` command
#  description: learn some of the most used options that `ls` command has
#  event: issue_commented.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: Finding files with `find` command
# - title: Search for files
#  description: Use `find` command to look for files by name
#  event: issue_commented.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: Options for the `find` command
# - title: Learn some of the options `find` command has
#  description: a description of the step, shown to the learner in the course progress page
#  event: issue_commented.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: Combine commands - combine learned commands
# - title: Combine the 2 commands 
#  description: Learn to chain together commands
#  event: issue_commented.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

